### ISSUE TITLE
pulldata("pantheria") not working

### ISSUE THREAD

**Issue by rplewes** [EcologicalTraitData/traitdataform#43]
There is an error in pantheria.R code that is causing pulldata("pantheria") not
to work.

amniota needs to be changed to pantheria and
read.csv needs to be changed to read.delim

amniota <- utils::read.csv("PanTHERIA_1-0_WR05_Aug2008.txt",
                           fileEncoding = "UTF-8",
                           stringsAsFactors = FALSE)

pantheria  <- utils::read.delim("PanTHERIA_1-0_WR05_Aug2008.txt",
                           fileEncoding = "UTF-8",
                           stringsAsFactors = FALSE)

**Comment by JELLY1** [comment]
mammaldiet is also not working

`# to import a dataset`
`pulldata("mammaldiet")`

I get the following error: Direct call to data source failed. Please check internet connectivity and re-load data!

My internet connection is fine and I was able to load 'carabids'

**Comment by fdschneider** [comment]
As described in #47, those data URLs at Dryad are highly unstable and may break once in a while. Apparently they changed their API again. The original dataset is found at http://doi.org/10.5061/dryad.6cd0v.   

The call for the carabids dataset employs the package [suppdata](https://github.com/ropensci/suppdata), which takes care of changing URLs. 

I just updated this for mammaldata, but it is not on CRAN, so you would need to re-install the development version using `devtools::install_github('EcologicalTraitData/traitdataform')`.

**Comment by JELLY1** [comment]
Thank you very much.

**Comment by fdschneider** [comment]
Also, since the original issue topic was still unanswered, @rplewes @lauterbur, I fixed the pantheria script, too (e9c52fd). 
But since the pantheria dataset is very complex, further attributes and an extended thesaurus for mapping the traits would be required to enable the handling of this dataset into a standardised form. Pull requests to fill this gap are welcome (see how it is done for [arthropodtraits](https://github.com/EcologicalTraitData/traitdataform/blob/master/inst/extdata/arthropodtraits.R)). Otherwise I will remove those additional data from the package in the long run.
