### ISSUE TITLE
traitdataform not available from CRAN anymore (since April 30th 2021)

### ISSUE THREAD

**Issue by Rekyt** [EcologicalTraitData/traitdataform#44]
Hello `traitdataform` developers 👋 
I don't know to what extent you're still working on `traitdataform` but I wanted to warn you that it is not available on CRAN with the following message:
```
Archived on 2021-04-30 as check problems were not corrected in time. 
```
The check issues are available here: https://cran-archive.r-project.org/web/checks/2021/2021-04-30_check_results_traitdataform.html

It seems that there are two causes for the check errors:

1. The dataset `arthropodtraits` used in several places doesn't seem to be accessible through the package
2. A number of times a table is used but with duplicated `row.names` which make R complain

I can offer to try to make a PR to solve these issues and help have `traitdataform` back on CRAN as I think it's important that this package is accessible to a maximum number of people!

Thanks :)

**Comment by fdschneider** [comment]
Dear Matthias,
 
thanks for reaching out and for your offer to help. I am aware of the unavailability on CRAN. Unfortunately I was not able to dedicate the time necessary to fix the issues until now (I am the only maintainer of the package and moved into a different field, where this does not fit in the job description). 

As far as I've seen, the issues are caused by changes in the lazy loading behaviour of R, affecting the way the pulldata function loads the external data objects. But I need to look deeper into that. Any suggestions for the solution would be very welcome (as Pull request or discussion thread here). 

The other pending issue is the update of the CI to Github Actions, as travis.ci stopped supporting open source projects for free.  Without these testing environments, I will not be able to submit the package back to CRAN.

**Comment by fdschneider** [comment]
The package is back on CRAN since yesterday, but has issues with the external sources required for testing. I'll open a new issue with a suggestion how to fix this.
